### ISSUE TITLE
annoy C++ Build Tools dependency

### ISSUE THREAD

**Issue by ryEllison** [VarIr/scikit-hubness#53] opened 2020-01-16 03:45 UTC
Below is a truncated version of my post-review comment bringing this issue to your attention -

"...the annoy dependency threw an error and exited because of it's need for Visual Studio C++ Build Tools... However, I tested this package on a new laptop that I had yet to install C++ Build Tools... I suppose its need is handled in the error message of annoy..."

I don't have the error message as you requested because I installed C++ Build Tools onto my machine. Perhaps create a virtual windows environment, install and configure python, and attempt pip installation. This should result in the error message I ran into...

**Comment by ivan-marroquin** [comment] 2021-05-24 15:39
Hi all,

There is another alternative to annoy package for nearest neighbors that it seems to be faster and supports several distance metrics. The package in question is pyNNDescent at https://pynndescent.readthedocs.io/en/latest/api.html

Ivan

**Comment by VarIr** [comment] 2021-07-01 10:30
Could not reproduce, and no other affected users so far, thus closing. 
If users run into similar problems, feel free to comment or open a new issue.

**Closed by VarIr** 2021-07-01 10:30 UTC
